[package]
name = "example-02-bench"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
tungsten = { workspace = true }
glam = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
